Ncnews 7
abath257/Northcoders_News pull request #6
Opened 2022-05-18 14:01 UTC by abath257

1. Refactored /api/articles/:article_id to include comment count
2. Made new describe block to test this tiskct.

2022-05-18 14:34 UTC, emilyb93 commented on __tests__/app.test.js
> +  test("status 200 : Returns the article given in the endpoint, with the username as the author and added comment count", () => {
This is a test for the same behaviour as the previous test, we dont need it

2022-05-18 14:37 UTC, emilyb93 commented on models/articles_model.js
> +    .query("ALTER TABLE articles ADD comment_count INT")
We do not want to add the comment as a new column, we want to be getting the comment count in a SELECT query. Also this doubles your time and queries made. 

Have a look at how to get your comment count within a SELECT statement, have a look into COUNT(), LEFT JOIN, and GROUP BY as a starting point, and be sure to check the notes app!

2022-05-18 14:37 UTC, emilyb93 requested changes
Please refactor your comment count query

2022-05-19 08:19 UTC, cjplatten approved these changes
Looks good!

2022-05-19 08:26 UTC, merged